site_name: RSK's test doc
pages:
    - Home: index.md
    - Training materials: README.md
    - Data Visualization: data_viz.md
theme: 
    name: 'material'
    include_sidebar: false
    palette:
        primary: 'White'
        accent: 'Light Green'
    logo: 'images/dna-sequence-1600x800.jpg'
extra_css: [extra.css]
